rsksmart/rLogin

- sample/with_be/front/index.html
- `provider` has the same issue discovered in #10. Lack of polymorphism :( this was easy fixed using get accounts avoiding `if type of provider is...`
- Adds reset button that deletes local storage. Now is faster to test 👍 
Related to #10, I added this PR into RSK Wallet Connect POC https://github.com/rsksmart/RSKWalletConnect/pull/1. That can be used to test _open_ flavor :)
If this changes are ok, this branch can be merged into `add-wallet-connect`. After this, we can merge `add-wallet-connect` into `master`
> Fix from in send transaction

- package.json
- sample/front/index.html
- src/components/Core.tsx
This PR was opened after analysing different approaches to handle Nifty wallet support for rLogin. The problem is correctly described on this PR https://github.com/rsksmart/rLogin/pull/15
This new PR was tested with:
- Metamask Ethereum mainnet and RSK mainnet
- Nifty wallet Ethereum mainnet and RSK mainnet
- Trust wallet + Wallet connect with Ethereum mainnet
Changes:
- Implements `if nifty` to use `send` instead of `request` on rLogin core
- Implements `if nifty` in sample app too
> Nifty wallet support

- package.json
- src/components/shared/Typography.tsx
Add margin explicitly in if "host" CSS has `margin: 0` on p and h3. 
Fixes import issue in the RNS Manager.
> Add margin to paragraph and header3.

- package-lock.json
- sample/front/index.html
Check if window.ethereum exists before setting the autorefresh setting in the sample app.
- Setting has to do with Metamask, in the case that window.ethereum is not loaded, the app should not break. I.e. when using only Wallet Connect
- package-lock.json changes were done by npm
Resolves #44
> Allow user to only have WalletConnect for the sample apps

- README.md
- package-lock.json
- package.json
- sample/front/index.html
- src/Core.tsx
- src/RLogin.tsx
- src/components/shared/RLoginButton.tsx
- src/lib/data-vault.ts
- src/lib/did-auth.ts
- src/ui/shared/Button.tsx
- src/ux/step2/SelectiveDisclosureRequest.tsx
- src/ux/step2/SelectiveDisclosureResponse.tsx
- src/ux/step2/index.tsx
- src/ux/step3/ConfirmSelectiveDisclosure.tsx
This PR includes multiple fixes and improvements described below. The biggest is the response of `rLogin.connect()` which is a **breaking change**.
- DataVault:
- Updates `@rsksmart/ipfs-cpinner-client` to `beta.9`
- Endpoint now pointing to `/v2`
- When accessing the datavault and signing messages for the permissioned version, buttons are disabled. This closes #59 
- If the user does not meet the standards of the backend, then show an error. This closes #46
- rLogin.connect() response **BREAKING CHANGE**
- .connect() or .connectTo() returns the following object:
```
{
provider: any,
dataVault: DataVaultWebClient | null // only if connect to the DV was initiated
disconnect: () => void // used to disconnect
}
```
- Adds the disconnect() function that removes the localStorage variables, …
> rLogin 1.0.0

- src/ui/modal/ModalBody.tsx
- src/ui/modal/ModalCard.tsx
- src/ux/step2/SelectiveDisclosureRequest.tsx
- src/ux/step2/SelectiveDisclosureResponse.tsx
Added wordBreak to the URL< however that wasn't enough.
Updated `ModalCard` to remove column, and then for `ModalBody` added in a maxWidth that matches the cards.
You can test with the sample app in the repo, change the backend URL to the production one: `https://data-vault-sample-backend.rlogin.identity.rifos.org`
Resolves #66
> Handle long URLs without breaking design

- sample/front/index.html
- src/Core.tsx
- src/constants/index.ts
When the user closes the modal by clicking on the `X`, the background, or the WalletConnect `X`, clear the cachedProvider. This way, the user has the option to select a different connection method. In addition, check if the provider is WalletConnect and remove that local storage variable also.
This does not remove the DataVault authentication, which will only be removed on a disconnect.
WalletConnect adds an additional local storage variable called `walletconnect` that was only being cleared when the user clicked 'disconnect'. What was happening was WC would try to use this variable even if the cached LS variable was cleared. This could sometimes prompt a QR code and not allow a user to choose another method.
Resolves #75
> Reset Wallet Connect

- README.md
- package.json
- src/Core.tsx
- src/adapters.ts
- src/lib/data-vault.ts
- src/lib/provider.ts
- src/ux/wrongNetwork/ChangeNetworkButton.test.tsx
- src/ux/wrongNetwork/ChangeNetworkButton.tsx
- src/ux/wrongNetwork/NetworkUnorderedList.ts
- src/ux/wrongNetwork/OtherNetworkSpan.ts
- src/ux/wrongNetwork/WrongNetworkComponent.test.tsx
- src/ux/wrongNetwork/WrongNetworkComponent.tsx
- src/ux/wrongNetwork/changeNetwork.ts
Changes the error when a user attempts to connect to an incorrect network. If the user is using Metamask, and one of the available networks is RSK, an option to connect (or configure) that network is presented:
If the user is not using metamask, the popup remains similar but the popup style is changed:
This should resolve #35, as instead of switching back to step1, it continues. 
Resolves #33 by adding Ethereum testnet names.
> Add or Switch to Network feature if on the wrong network.

- package.json
- sample/back/index.js
- src/Core.tsx
When backend sends error `INVALID_CHALLENGE_RESPONSE` rLogin will first fetch another challenge and try to sign it again. If that fails, error is displayed.
> Retry auth when challenge has expired

- package.json
- src/Core.tsx
Fixes an issue where the modal will not close when the provider is undefined.
> Check if provider is set first, then disconnect

- src/providers/injectedProviders.ts
- src/ux/step1/WalletProviders.test.tsx
- src/ux/step1/WalletProviders.tsx
Return empty string if there are no providers rather than checking if the non-existent one. Then update the UI to show a message about no providers. 
To test this, remove WalletConnect and Portis as providerOptions in `/sample/front/index.html` then disable Metamask from chrome. Start the app using `npm run sample:open. With zero providers, you should now see this message:
Resolves #104, reported by @antomor
> Show message if there are no providers

- sample/front/index.html
- src/Core.tsx
- src/RLogin.tsx
User can optionally set supported languages in the options object when initializing rLogin. If option `supportedLanguages` is not defined, all languages are supported by default.
> (US-93) feat: enable 'supportedLanguages' options

- cypress/integration/1-modal/rlogin-modal_spec.js
- package-lock.json
- package.json
- sample/front/index.html
- src/Core.tsx
- src/ui/modal/Modal.tsx
This made Ledger provider fail. As far as I remember, this was added to make the modal restart on closed manually. This is now a blocker, we can find a better strategy to do this latter.
> Make modal do not disconnect from Ledger on close

- src/ux/step1/Provider.test.tsx
- src/ux/step1/Provider.tsx
if the provider is disabled should not allow the user to click on it.
> fix bug user still click when provider is disabled

- cypress/integration/3-permissioned-app/permissioned_spec.js
Fixes the broken test that was reported in #155.
I suspect this happened after we merged different branches that didn't have the tests updated. No problem, this PR fixes the expected text and updates heading and button texts.
> Fix integration test that uses the new 'confirm' component.

- README.md
- sample/front/index.html
- src/Core.tsx
- src/RLogin.tsx
- src/controllers/providers.ts
- src/i18n.ts
- src/ui/shared/SelectDropdown.tsx
- src/ux/chooseNetwork/ChooseNetworkComponent.test.tsx
- src/ux/chooseNetwork/ChooseNetworkComponent.tsx
- src/ux/step1/WalletProviders.test.tsx
- src/ux/step1/WalletProviders.tsx
Allows the user to choose the network when selecting hardware wallets.
See detailed commit messages for full details.
To accomplish this the provider controller has been taken from web3modal (src/controllers/providers.ts). The majority of this file has stayed the same, the following things were added or changed:
* `onClick` method accepts an optional parameter with RPCURL and ChainId [here](https://github.com/rsksmart/rLogin/blob/choose-network/src/controllers/providers.ts#L146). This is how the whole thing works.
* `connectTo` method also accepts the optional parameter. [See here](https://github.com/rsksmart/rLogin/blob/choose-network/src/controllers/providers.ts#L180)
In the future, this file could be used to solve #106, and 
https://github.com/Web3Modal/web3modal/pull/300
> Choose network for hardware wallets

- src/components/shared/RLoginButton.test.tsx
- src/components/shared/RLoginButton.tsx
There were two issues here which I could not solve. 
1. the styled components were throwing an error and had something to do with versions, and outputting. I tried updating the peerDependecies but it still had an issue.
2. the themeProvider looked like it was expected since the colors were based on the theme.
This is only happening when we exported this single component and not with the rLogin modal. This component is also tiny and does not need to complexity of Styled components... so I converted it to plain old JavaScript CSS. 
What it looks like imported into a fresh cra:
Resolves #144
> Fix rbutton

- cypress/integration/1-modal/rlogin-retry-provider_spec.js
- cypress/integration/2-sample-app/providerError_spec.js
- package-lock.json
- src/Core.tsx
- src/controllers/providers.ts
- src/ui/shared/ErrorMessage.test.tsx
- src/ui/shared/ErrorMessage.tsx
Return the error from the provider to the UI so it can be displayed on the screen.  This is mostly for the new hardware wallets but will also work for the injected provider.
Resolves #106 
Ledger, trying to connect to RSK testnet using the RSK Ledger app. The error is set [from the provider](https://github.com/rsksmart/rLogin-providers/blob/develop/packages/rlogin-ledger-provider/src/LedgerProvider.ts#L52).
The injected provider will always throw "User Rejected." because of [this line in web3modal](https://github.com/Web3Modal/web3modal/blob/master/src/providers/connectors/injected.ts#L8). This is pulled by a few files before it gets to the provider controller. I don't know if it makes sense to fix this in this pr.
> Handle provider error

- src/Core.tsx
- src/RLogin.tsx
- src/lib/providerDisconnect.ts
Creates two functions, one for disconnect and one to close the modal. Then code is cleaned up to use one of the two functions. Disconnect updates the state as appropriate, but then delegates to a file in `lib/` to disconnect from the provider and the datavault.
The `componentDidUpdate` code that was added in XXXX was removed. This code was a workaround because at the time we were not handling the errors from the provider.  #168 handles this scenario and the code is now duplicative. 
Cypress tests are currently failing because the provider error is not being handled. Once #168 is merged, and this PR is rebased into it, the failing tests will pass.
> Refactor disconnect and closeModal methods

- cypress/integration/2-sample-app/cacheProvider_spec.js
- cypress/integration/2-sample-app/hardwareProvider_spec.js
- package.json
- sample/front/index.html
- src/Core.tsx
- src/RLogin.tsx
- src/controllers/providers.ts
- src/ux/confirmInformation/ConfirmInformation.tsx
Return the error that the provider could throw to the dapp. Also, hide the images if the userProviderOptions is undefined.
This is similar to #195 but without the try/catch block.
Solves the following things:
- Returns an error if the cachedProvider throws an error while reconnecting
- Saves hardware chooseNetwork settings to be reused when connecting with the cachedProvider.
- Adds simple test for hardware wallets connecting normally. 
We are unable to test hardware wallet cachedProvider since the provider will throw an error. This error is sent back to the dapp, but the current workflow is to fallback to show the main connect screen.
> Add tests and return error if cachedProvider provider throws an error

- package-lock.json
- package.json
- src/Core.tsx
- src/controllers/providers.ts
- src/ux/ChooseDPath.tsx
- src/ux/chooseNetwork/ChooseNetworkComponent.test.tsx
- src/ux/chooseNetwork/ChooseNetworkComponent.tsx
- src/ux/confirmInformation/ConfirmInformation.test.tsx
- src/ux/confirmInformation/ConfirmInformation.tsx
Adds dPath selection in 'Choose Network' step
> The traditional UX lets the user see the address associated to the derivation path in the "addresses table". This is not possible with the given `rLogin-providers` implementation. For that UX we should make a bigger change.
> Custom dPath

- .github/workflows/cypress.yml
- package.json
- sample/front/index.html
- src/Core.tsx
- src/adapters.ts
- src/i18n.ts
- src/lib/hardware-wallets.ts
- src/ux/chooseDpath/AccountRow.tsx
- src/ux/chooseDpath/ChooseDPath.tsx
- src/ux/chooseNetwork/ChooseNetworkComponent.tsx
- src/ux/confirmInformation/ConfirmInformation.tsx
This uses the existing 'Choose Network' screen before connecting, but then if the wallet isLedger or isTrezor, it will prompt the user to select an account/dpath.
- Shows five accounts at a time and saves the loaded ones in memory. 
- Shows balance of those accounts using bignumber.js which was already a dependency.
- The provider is now responsible for the selected dPath, not rLogin
- Connects to the device to get the next set of accounts
- Disables 'select' button when choosing a network. Closes #205
- do not send Cypress results externally. We are out of credits and this was causing the build to fail 
Changes in the providers is in [this PR](https://github.com/rsksmart/rLogin-providers/pull/42). It is currently pending the Trezor integration. See that PR for description of the changes. …
> Show balance and address with dPath selection

- src/constants/cssSelectors.ts
- src/ux/step1/Provider.test.tsx
- src/ux/step1/Provider.tsx
- src/ux/step1/WalletProviders.test.tsx
- src/ux/step1/WalletProviders.tsx
- Adds a new flag `hideIfDisabled` to each `<Provider` and will hide them if `true`.
- Removes `UserProvider` component as it was a unnecessary middleman to `<Provider`
- Refactored `<Provider` to take a single `userProvider` variable that may or maynot contain `onClick`
Example of Tally and Wallet Connect
Showing everything but with Metamask as the injected provider
The best way to smoke test would be to comment out different providers
> Hide providers if they are disabled

- package-lock.json
- package.json
- sample/front/index.html
- src/Core.tsx
- src/constants/index.ts
- src/i18n.ts
- src/ux/chooseDpath/ChooseDPath.tsx
- src/ux/chooseNetwork/ChooseNetworkComponent.test.tsx
- src/ux/chooseNetwork/ChooseNetworkComponent.tsx
Allows the user to use the Ethereum derivation path when connecting to a network that is not Ethereum. This is to assist users who were previously using Metamask to connect their hardware wallets. 
**upfront**
**after connecting**
This will require a small change in the providers to select the correct path.
> Allow user to select Ethereum Path when connecting to RSK

- src/ux/chooseNetwork/ChooseNetworkComponent.tsx
For whatever reason, the checkbox component must be wrapped by an element that is `display: 'flex'`.
> Fix checkbox that was not checkable

- cypress/integration/4-mobile/mobile-integration.js
- src/ux/step1/WalletProviders.tsx
WalletConnect was hidden on mobile viewports, this removes that requirement. Also, CY test for mobile.
Resolves #226
> Show WalletConnect on mobile viewport

- src/ux/chooseDpath/AccountRow.tsx
- src/ux/chooseDpath/ChooseDPath.tsx
- Changes the hover color for the selected row to a color that works on both light and dark mode.
- Adds hover color
- Removes input background color for better design with dark mode
Resolves #234
> Modify theme colors when choosing derivation path

- src/RLogin.tsx
- src/ui/modal/ModalLightbox.tsx
There were two fonts that were requested when running rLogin, `Rubik` and `Roboto`. Both of these fonts are san-serif fonts and if the browser does not have them, `Roboto` had [a fallback](https://github.com/rsksmart/rLogin/blob/develop/src/ui/shared/Typography.tsx#L10) to `sans-serif` . However, the `Rubik` font declaration had no fallback and by default browsers will use `serif`. This results in the ugly typography found in recent screenshots:
This PR defaults all font-family properties to a single source with a fallback of 'sans-serif'.
> Use the typeShared property instead of a single font.

- cypress/integration/2-sample-app/cacheProvider_spec.js
- src/constants/index.ts
- src/controllers/providers.ts
Now web3modal local storage `WEB3_CONNECT_CACHED_PROVIDER` is ignored
> fix: remove web3modal local variable dependency

- .github/workflows/cypress.yml
- cypress/integration/2-sample-app/cacheProvider_spec.js
- cypress/integration/2-sample-app/sampleDapp_spec.js
- cypress/integration/3-permissioned-app/permissioned_spec.js
- src/Core.test.tsx
- src/Core.tsx
- src/RLogin.tsx
- src/ux/confirmInformation/ConfirmInformation.test.tsx
- src/ux/confirmInformation/ConfirmInformation.tsx
Hides the confirmScreen flash that happens as a result of the component showing and then deciding to hide. A new function called `shouldConfirmShow` was added in the Core to get the variable from localStorage and make the determination. 
This PR also limits RLogin's access to the Core's state and only allows show and to set a screen.
> Refactor when/how confirmInformation is shown

- .github/workflows/cypress.yml
- src/Core.tsx
- src/RLogin.tsx
Rather than using `window.showRLoginModal`, create a reference to Core that can be called from RLogin to trigger the show and step variable. With this approach, it does not require a breaking change and removes setting the window variable.
Resolves #231
> Remove window.rLogin reference

- cypress/integration/1-modal/rlogin-modal-theme_spec.js
- cypress/integration/1-modal/rlogin-networks_spec.js
- cypress/integration/1-modal/rlogin-retry-provider_spec.js
- cypress/integration/1-modal/rlogin-triggers_spec.js
- cypress/integration/1-modal/rlogin-user-confirmation_spec.js
- cypress/integration/2-sample-app/cacheProvider_spec.js
- cypress/integration/2-sample-app/hardwareProvider_spec.js
- cypress/integration/2-sample-app/providerError_spec.js
- cypress/integration/2-sample-app/sampleDapp_spec.js
- cypress/integration/2-sample-app/wrongNetwork_spec.js
- cypress/integration/3-permissioned-app/permissioned_spec.js
- cypress/integration/account.js
- package-lock.json
- package.json
- sample/front/index.html
Closes #264 
**This one is also chained with the others! I am using a refactor done in tests**
I couldn't reproduce the issue. I have added an integration test following the steps:
```ts
// before each: inject metamask + open popup
it('shows wallet info in light after switching', () => {
switchTheme()
cy.contains('MetaMask').click()
cy.get('.rlogin-button.confirm').click()
cy.get('#showInfo').click()
testIsLight()
})
```
To test it I added `defaultTheme: urlSearchParams.get('defaultTheme') || 'light',` to sample app config
Took some time for some additional work:
- added some more tests to themes
- refactored `new MockProvider` as a factory method. It accepts setup overrides + a function that is run on provider before loading it into the screen to be able to add extra things like …
> Theme testing

- .github/workflows/audit.yml
- cypress/integration/1-modal/rlogin-providers_spec.js
- package.json
- src/ux/step1/WalletProviders.tsx
Title is the primary update, however, what started as a very easy fix revealed a security issue with a dependency used in the testing framework. Fixing this error then illuminated issues in our tests with a missing typescript property as well as a missing polyfills. Fixing these then had issues with the install.
I have changed the npm audit command to only run on production dependencies and reverted the package updates. 
Resolves #278
> Hide nifty wallet unless the user has it enabled
