rsksmart/rLogin

.gitignore, jest.config.js, package-lock.json, package.json, src/components/Modal.test.tsx, test/LocalStorageMock.ts, test/setupTests.ts, tsconfig.json
- Adds enzyme testing
- Create mock class for localStorage
- Create basic test for Modal.tsx and mock variables as proof of concept to be expanded later.
=> Add testing framework

package.json
=> Bump to beta 1

package.json, src/components/Core.tsx, webpack.config.js
=> LGTM fixes

package.json
You can test it with `npm publish --dry-run`
=> Add build to prepublish

sample/front/index.html
Add RSK Testnet and Mainnet to sample app
=> Fix sample app networks

README.md, sample/front/index.html
Metamask is now preventing auto refresh by default
=> Remove autoRefreshOnNetworkChange

src/components/shared/RLoginButton.tsx, src/index.ts
An exportable button with styles.
=> Exportable button

package-lock.json, package.json, src/Core.tsx, src/lib/data-vault.ts, src/lib/provider.ts, src/ux/step3/ConfirmSelectiveDisclosure.tsx
Use the latest package of the cpinner-client `beta.7` which has support for encryption. 
Also fixes an issue where selective disclosures are not needed, but the code was looking to parse the response.
=> Use Encryption with the DataVault

sample/front/index.html
- Fix typo that caused the issue when signing with WC in sample dapp
- Upgraded WalletConnect
Closes #43
=> Fix typo that caused the issue when signing with WC in sample dapp

README.md
=> Add liquality to readme

sample/back/index.js
From security audit RLOGIN-007
=> Fix Hardcoded Secrets

package-lock.json, package.json, src/Core.tsx, src/lib/data-vault.ts, src/lib/provider.ts, src/vc-json-schema-adapter.ts
- Adds new Data Vault version
- Updates Data Vault URL
- Uses `@rsksmart/vc-json-schema-parser`
- Fixes `isNiftyWallet` check
=> Add new Data Vault encryption

package-lock.json, package.json, src/Core.tsx
Modal was closing even with network mismatch
=> Fix supported chains

sample/front/index.html
Remove the check for `isNifty` as they have resolved the issue. 
Reference: https://github.com/poanetwork/nifty-wallet/issues/421.
=> Remove nifty check as issue has been fixed.

package.json, sample/front/index.html
- Remove nifty check as they fixed this issue. (#76)
=> Release v1.0.3

package.json
=> Bump to v1.0.4

package.json, sample/front/index.html, src/Core.tsx, src/constants/index.ts
=> Release v1.0.4

package.json
=> Bump to v1.0.7

package-lock.json, package.json, src/Core.tsx, src/ui/shared/Loading.tsx, src/ux/step2/SelectiveDisclosureRequest.tsx, src/ux/step2/index.tsx, src/ux/step3/ConfirmSelectiveDisclosure.tsx
Expand the loading component from the Portis PR to include a message. The waiting times, in order, are these:
1. Connecting to provider
2. Connecting to server
3. Connecting to the DataVault
4. Confirming Identity
Also combines the `disconnectProvider` function from handleClose and disconnect.
=> Add loading messages to the loading wheels

package.json
=> bump to v1.1.0

sample/front/index.html
This fixes data vault fetch error
=> fix: use url string instead of object

cypress/integration/1-modal/rlogin-retry-provider_spec.js, src/Core.tsx
fixes reconnecting after a failed connect issue
Resolves #103
=> US-60- Fix reconnecting after a failed connect issue

cypress/integration/2-sample-app/wrongNetwork_spec.js, sample/front/index.html, src/Core.tsx
Enable the component to allow any network in non is configured a supported
Closes #25
=> US-67- fix optional supported networks

package.json, sample/front/index.html, webpack.config.js
Fix the types export
Closes #51
=> Include types in build output

src/Core.tsx, src/RLogin.tsx
Selected language is included in the response when rLogin connection is created
=> (US-94) feat: include selectedLanguage on response when connected

src/ux/step1/WalletProviders.tsx
=> feat: hide selector when only one option available

package.json
=> Bump to v1.1.2

package.json
=> Bump to v1.1.3

.github/workflows/ci.yml, .github/workflows/cypress.yml
Remove push condition and specific branches and only run on all pull requests.
=> Remove ci for push

cypress/integration/3-permissioned-app/permissioned_spec.js, package-lock.json, sample/back/index.js, src/Core.tsx
If backend throws a validation error, it will show it in this screen.
=> fix backend error messages

package.json
=> Bump to v1.2.0-beta.3

src/ux/step1/WalletProviders.tsx
=> Move Torus provider into 3rd row

cypress/integration/2-sample-app/cacheProvider_spec.js, cypress/integration/2-sample-app/hardwareProvider_spec.js, package.json, sample/front/index.html, src/Core.tsx, src/RLogin.tsx, src/controllers/providers.ts, src/ux/confirmInformation/ConfirmInformation.tsx
- Fix cached provider for hardware devices
=> v1.3.0-beta.3

README.md, package.json
=> Bump to v1.3.0

package-lock.json, sample/front/index.html, src/Core.tsx, src/controllers/providers.ts, src/lib/hardware-wallets.ts, src/lib/networkOptionsTypes.ts, src/ux/chooseNetwork/ChooseNetworkComponent.tsx
https://user-images.githubusercontent.com/8353287/145475622-19971e71-6e1c-42dd-b679-c3562cc10c35.mov
=> select portis network before connect

package-lock.json, package.json, sample/front/index.html, src/Core.tsx, src/controllers/providers.ts, src/lib/hardware-wallets.ts, src/lib/networkOptionsTypes.ts, src/ux/ChooseDPath.tsx, src/ux/chooseNetwork/ChooseNetworkComponent.test.tsx, src/ux/chooseNetwork/ChooseNetworkComponent.tsx, src/ux/confirmInformation/ConfirmInformation.test.tsx, src/ux/confirmInformation/ConfirmInformation.tsx
=> v1.3.1-beta.1

.github/workflows/audit.yml, README.md, cypress/integration/3-permissioned-app/permissioned_spec.js, package-lock.json, package.json, sample/front/index.html, src/Core.tsx, src/RLogin.tsx, src/constants/index.ts, src/lib/did-auth.ts, src/lib/providerDisconnect.ts, webpack.config.js
Fixing report results from security assessment
=> Security assessment feb 2022

package.json
=> Bump to v1.3.1

src/RLogin.tsx
=> fix overriding the dark theme

package.json
=> Bump to v1.3.2

package-lock.json, package.json, webpack.config.js
Update settings for webpack to watch the /src folder.
Closes #241
=> Adds webpack server and updates watch settings

src/i18n.ts, src/ux/chooseNetwork/ChooseNetworkComponent.test.tsx, src/ux/chooseNetwork/ChooseNetworkComponent.tsx
=> Show network only when there is a single option

cypress/integration/1-modal/rlogin-retry-provider_spec.js, cypress/integration/2-sample-app/cacheProvider_spec.js, cypress/integration/2-sample-app/hardwareProvider_spec.js, cypress/integration/2-sample-app/providerError_spec.js, cypress/integration/2-sample-app/sampleDapp_spec.js, cypress/integration/2-sample-app/wrongNetwork_spec.js, cypress/integration/3-permissioned-app/permissioned_spec.js, package-lock.json, package.json
=> Upgrade mock-web3-provider

cypress/integration/1-modal/rlogin-user-confirmation_spec.js, src/Core.tsx, src/i18n.ts
=> fix: ask user to confirm in wallet

package.json
=> Bump to v1.3.3-beta.1

package.json
=> Bump to v1.3.4-beta.1

.github/workflows/cypress.yml, package-lock.json, package.json, src/Core.tsx, src/RLogin.tsx
=> Release v1.3.4-beta.1

src/providers/injectedProviders.ts, src/ux/step1/WalletProviders.tsx, src/ux/step1/extraProviders.ts
Adding BlockWallet as provider.
=> Add BlockWallet as a web provider.
